### Numpy continuation:

* Introduction of Numpy
* Created arrays in different dimensions.
* Accessing of array elements.
* shape and reshape of arrays

### Iteration of arrays:

In [5]:
import numpy as np
a = np.array([1,2,3,4,'a','b'])   ### 1-d array 
a

array(['1', '2', '3', '4', 'a', 'b'], dtype='<U11')

In [6]:
for i in a:
    print(i,end = " ")

1 2 3 4 a b 

In [7]:
### 2-d array:

b = a.reshape(3,2)
b

array([['1', '2'],
       ['3', '4'],
       ['a', 'b']], dtype='<U11')

In [8]:
b.ndim

2

In [12]:
for i in b:   ### i holds the row
    for j in i:    ### j holds elements  of row
        print(j,end = " ")
    

1 2 3 4 a b 

In [11]:
### 3-d array:

c = a.reshape(2,1,3)
c

array([[['1', '2', '3']],

       [['4', 'a', 'b']]], dtype='<U11')

In [13]:
for i in c:       ### 2-d array
    for j in i:  ####  row
        for k in j:  ### element of row
            print(k,end =" ")

1 2 3 4 a b 

In [16]:
### keyword for iterating the array:

### np.nditer()

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 a b 

### Joining of arrays:

In [18]:
### 1-d array:

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
### 2-d array:

c = a.reshape(2,2)
d = b.reshape(2,2)
e = np.concatenate((c,d))
e

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
#### 3-d array:

a = a.reshape(2,1,2)
b = b.reshape(2,1,2)
c = np.concatenate((a,b))


In [21]:
c

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]]])

* **Note :** 

  To concatenate The shape and dimension should be same .

### Stastical and Mathematical Opeartions on arrays:

In [24]:
a = np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
np.min(a)  ### minimum value in the array

1

In [26]:
np.max(a)  ### maximum value in the array

10

In [27]:
np.argmax(a)   ### index of maximum value

9

In [28]:
np.argmin(a)   ### index of minimum value

0

In [29]:
a.mean()   ### mean of entire array

5.5

In [31]:
np.median(a)   ### median of the array

5.5

In [33]:
np.var(a)   ### variance of the array elements

8.25

In [34]:
np.average(a) ### average of the array elements

5.5

In [35]:
np.std(a)  ## standard deviation of the array elements

2.8722813232690143

In [36]:
np.sum(a)  ### sum of all array elements

55

In [37]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
np.min(a,1)   ### 1 --- row 

array([1, 3, 5, 7, 9])

In [39]:
np.min(a,0)  ### 0---- column

array([1, 2])

In [40]:
np.sum(a,0)

array([25, 30])

In [41]:
np.argmin(a,1)

array([0, 0, 0, 0, 0], dtype=int64)

In [42]:
np.argmin(a,0)

array([0, 0], dtype=int64)

### Stacking:

* Organising /arranging in an proper order.
    * vertical stacking 
    * Horizontal stacking

In [44]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [51]:
np.hstack((a,b))

array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [50]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [47]:
b = a

In [48]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [52]:
np.sqrt(a)  ### square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766]])

In [53]:
np.exp(a)  ### exponential value

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [54]:
np.sin(a)  ### sine values of the array elements

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111]])

In [55]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003],
       [-0.91113026, -0.83907153]])

In [56]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128],
       [-3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146],
       [-0.45231566,  0.64836083]])

In [57]:
np.log(a)   ### logarithamic values of array elements

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [59]:
np.log2(a) ### log values with base 2

array([[0.        , 1.        ],
       [1.5849625 , 2.        ],
       [2.32192809, 2.5849625 ],
       [2.80735492, 3.        ],
       [3.169925  , 3.32192809]])

In [60]:
np.remainder(a,4)

array([[1, 2],
       [3, 0],
       [1, 2],
       [3, 0],
       [1, 2]], dtype=int32)

In [62]:
np.degrees(a)

array([[ 57.29577951, 114.59155903],
       [171.88733854, 229.18311805],
       [286.47889757, 343.77467708],
       [401.07045659, 458.3662361 ],
       [515.66201562, 572.95779513]])

In [63]:
np.diff(a)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [64]:
np.ediff1d(a)  ### converts array into 1-d and finds the difference

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [66]:
np.i0(a)   ### Bessel function


array([[   1,    2],
       [   4,   11],
       [  27,   67],
       [ 168,  427],
       [1093, 2815]])

In [67]:
np.mod(a,4)

array([[1, 2],
       [3, 0],
       [1, 2],
       [3, 0],
       [1, 2]], dtype=int32)

In [69]:
np.power(a,3)

array([[   1,    8],
       [  27,   64],
       [ 125,  216],
       [ 343,  512],
       [ 729, 1000]], dtype=int32)

In [71]:
np.reciprocal(a,dtype = float)

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667],
       [0.14285714, 0.125     ],
       [0.11111111, 0.1       ]])

In [72]:
np.multiply(a,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [73]:
np.divide(a,2)

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ],
       [3.5, 4. ],
       [4.5, 5. ]])

In [75]:
a = np.array([1+2j,2+3j,3+4j])
a

array([1.+2.j, 2.+3.j, 3.+4.j])

In [76]:
np.real(a)

array([1., 2., 3.])

In [77]:
np.imag(a)

array([2., 3., 4.])

### Ravel and Flatten :

* Ravel : Function which is used to make copy of original array.When we make any changes in the copy of original array,those will also applicable in original array.

* Flatten  : Function which is used to make copy of original array.When we make any changes in the copy of original array,those will not applicable in original array.



In [78]:
original = np.array([1,2,3,4,5])   ## original
original

array([1, 2, 3, 4, 5])

In [79]:
### ravel:

rav = original.ravel()
rav    ### copy

array([1, 2, 3, 4, 5])

In [81]:
rav[0] = 11

In [82]:
rav

array([11,  2,  3,  4,  5])

In [83]:
original

array([11,  2,  3,  4,  5])

In [84]:
### Flatten:

original

array([11,  2,  3,  4,  5])

In [86]:
flat = original.flatten()
flat

array([11,  2,  3,  4,  5])

In [87]:
flat[0] = 1

In [88]:
flat

array([1, 2, 3, 4, 5])

In [89]:
original

array([11,  2,  3,  4,  5])

### Random Methods:

In [103]:
np.random.randint(100)  ### integer value within the gievn range.

73

In [104]:
np.random.rand() ### float value within 0 and 1

0.21664250582465128

In [109]:
np.random.randint(100,size = (20)) ### generates defined number of random integer values within the given range

array([ 5, 70, 30, 98, 69, 85, 30, 84, 23,  7, 18, 67, 37, 21, 89, 29, 74,
       11, 45, 26])

In [112]:
np.random.randint(100,size = (3,3,3))

array([[[53, 33, 99],
        [81, 32, 50],
        [26, 29, 37]],

       [[43, 53, 33],
        [66, 25, 31],
        [ 2, 57, 28]],

       [[30, 78, 87],
        [23, 35, 26],
        [44, 71, 53]]])

In [125]:
np.random.choice([1,2,3,4,5,6])


2

In [131]:
np.random.choice([1,2,3,4,5,6],size = (3,3))

array([[6, 3, 4],
       [1, 1, 5],
       [6, 5, 5]])

In [142]:
a = np.random.choice([1,2,3,4,5,6],p = [0,0.1,0.2,0.4,0.1,0.2],size = ((4,3)))
a

array([[3, 4, 2],
       [2, 2, 4],
       [2, 6, 4],
       [3, 6, 6]])

In [152]:
np.random.shuffle(a)
a

array([[3, 4, 2],
       [2, 2, 4],
       [3, 6, 6],
       [2, 6, 4]])

In [154]:
np.random.randn(10)   ### positive and negative values

array([-0.79443182,  0.38494216,  0.18350702,  0.71954146,  0.93339814,
        0.78780975,  0.21054818,  1.07123683,  0.52443949, -0.0605745 ])

In [155]:
np.random.normal()

-0.7837311834093482

In [161]:
np.random.binomial(10,p=[0.1],size = ((2,2)))

array([[0, 2],
       [1, 1]])

### Array Filtering:

In [162]:
a = np.array([1,2,14,22,91,95,10])
b = [True,True,True,False,True,False,False]
c = a[b]
c

array([ 1,  2, 14, 91])

In [163]:
### print the values which are greater than 14:

b = []
for i in a:
    if i > 14:
        b.append(True)
    else:
        b.append(False)
c = a[b]
c

array([22, 91, 95])

In [164]:
d = a > 14

In [165]:
d

array([False, False, False,  True,  True,  True, False])

In [166]:
c = a[d]

In [167]:
c

array([22, 91, 95])

In [171]:
a = np.array([1,2,3,5])
b = np.array([4,5,6,7])
np.dot(a,b)

67

In [173]:
a.T

array([1, 2, 3, 5])