### Numpy:


In [1]:
### Installing the library:


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
### Importing the library:

import numpy as np

### Creating arrays using numpy:


##### 1-d array:


In [6]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a.dtype   ### datatype of the elements


dtype('int32')

In [9]:
a = np.array([1,2,3,'a'])
a

array(['1', '2', '3', 'a'], dtype='<U11')

In [10]:
a.dtype

dtype('<U11')

In [15]:
a = np.append(a,10)  ### appending a single element
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a = np.append(a,[11,12,'b'])  ### appending group of elements
a

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'b',
       '11', '12', 'b', '11', '12', 'b', '11', '12', 'b'], dtype='<U11')

In [20]:
a = np.arange(1,10)   ### array within a range
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(0,10,2)   ### range with step
a

array([0, 2, 4, 6, 8])

In [23]:
a.nbytes  ### memory occupied by array

20

In [25]:
a.itemsize  ### memory occupied by each element


4

In [27]:
len(a)  ### number of elements presnt in an array.

5

In [28]:
a = np.linspace(1,10,20)  ###creating an array with required number of elements with the arange.
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
len(a)

20

In [31]:
a = np.logspace(1,10,20)   ### logarithimic values
a


array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [33]:
np.full(10,"numpy")  ## repeating a particular element required number of times.

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [34]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [36]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
a.ndim

1

##### 2-d array:  
* combination of more 1-d arrays is 2-d array.

In [40]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
b.ndim   ### checking the dimension

2

In [43]:
b.dtype

dtype('int32')

In [44]:
b.nbytes

48

In [45]:
b.itemsize

4

In [46]:
len(b) ### number of rows in the array

3

In [47]:
b.size    ### total number of elements present in the array

12

##### 3-d array:

* combination of more 2-d arrays is 3-d array.

In [48]:
c = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[8,9,7]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [8, 9, 7]]])

In [49]:
c.ndim

3

In [50]:
len(c)  ## number of 2-d arrays present

2

In [51]:
c.nbytes

48

In [52]:
c.itemsize

4

In [53]:
c.size

12

###### Multi dimensional array:

In [60]:
d = np.array([1,2,3,4,5],ndmin = 10)

In [61]:
d

array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]])

In [62]:
d.ndim

10

### Accessing elements from the array:

In [64]:
### 1-d array:

a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
a[-1]

20

In [66]:
a[0]

10

In [67]:
a[5]

15

In [68]:
a[:2]

array([10, 11])

In [69]:
a[-4:]

array([17, 18, 19, 20])

In [71]:
### 2-d array:

b = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [72]:
b[0]

array([1, 2, 3, 4])

In [73]:
b[1]

array([5, 6, 7, 8])

In [74]:
b[-1]

array([2, 4, 6, 8])

In [77]:
b[0,-2]   ### row index,element index

3

In [78]:
b[-1,-1]

8

In [79]:
b[1:,-2:]

array([[7, 8],
       [6, 8]])

In [80]:
b[:,-1]

array([4, 8, 8])

In [81]:
b[:,1:3]

array([[2, 3],
       [6, 7],
       [4, 6]])

In [82]:
### 3-d array:

c = np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [83]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
c[-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [85]:
c[0,0]

array([1, 2, 3])

In [88]:
c[0,0,-1]   ### array_index,row_index,element_index

3

In [89]:
c[:,-1]

array([[4, 5, 6],
       [3, 2, 1]])

In [90]:
c[:,:,-1]

array([[3, 6],
       [4, 1]])

### Shape of the arrays:

In [91]:
## 1-d array:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [92]:
a.shape

(11,)

In [93]:
### 2-d array:

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [94]:
b.shape  ## rows,columns

(3, 4)

In [95]:
### 3-d array:

c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [97]:
c.shape  ### 2-d array,rows,columns

(2, 2, 3)

### Reshaping of arrays:

*  giving a new shape to the array.

In [99]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
b = a.reshape(3,3)  ### 2-d array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [103]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
c = a.reshape(3,3,1)
c

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [107]:
a.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [110]:
a.reshape(3,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [111]:
a.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
a.reshape(-1,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [114]:
### create the arrays with all the different datatypes available.